### ISSUE TITLE
Cannot get SVG asset

### ISSUE THREAD

**Issue by Timvdv** [athombv/com.danfoss#3]
Got this after installing:

![schermafbeelding 2016-10-22 om 00 32 20](https://cloud.githubusercontent.com/assets/979227/19613794/44e28e30-97ef-11e6-8bd0-8d30e886e94d.png)

**Comment by mruiter** [comment]
Yep they forgot the learnmode picture

**Comment by Timvdv** [comment]
@mruiter haha, if you think about it.. I'm wondering if this has anything to do with the fact that it also won't pair. maybe because of the JS errors?

**Comment by mruiter** [comment]
I got them paired without trouble lc12 and 13

Do a complete reset to default before you pair on the danfoss 


Outlook voor Android






On Sat, Oct 22, 2016 at 11:19 AM +0200, "Tim van de Vathorst" <notifications@github.com> wrote:












@mruiter haha, if you think about it.. I'm wondering if this has anything to do with the fact that it also won't pair. maybe because of the JS errors?

**Comment by RobinBol** [comment]
This error is merely the result of a missing .svg element. This can not interfere with the pairing process, I removed the reference to the missing image, so this issue should be fixed.
